name: Publish Python Package

on:
  push:
    tags:
      - 'v*'  # Executa o fluxo quando um novo tag começando com 'v' é adicionado.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Faz checkout do repositório
      - name: Checkout code
        uses: actions/checkout@v3

      # Configura o Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9  # Versão do Python

      # Instala dependências
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      # Constrói os arquivos da biblioteca
      - name: Build the package
        run: python -m build

      # Publica no PyPI
      - name: Publish to PyPI
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          twine upload dist/*
